/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { MatiCoin } from "./MatiCoin";
export type { IMatiCoin } from "./IMatiCoin";
export type { MatiCoinVesting } from "./MatiCoinVesting";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { MatiCoin__factory } from "./factories/MatiCoin__factory";
export { IMatiCoin__factory } from "./factories/IMatiCoin__factory";
export { MatiCoinVesting__factory } from "./factories/MatiCoinVesting__factory";
